// products.js
export const allProducts = [
  { id: 1, nome: "Coxinha de Frango", preco: 8.0, quantidade: 0, unidade: 1 },
  { id: 2, nome: "Pastel de Forno", preco: 7.0, quantidade: 0, unidade: 1 },
  { id: 3, nome: "Quiche", preco: 7.0, quantidade: 0, unidade: 1 },
  { id: 4, nome: "Enroladinho", preco: 6.0, quantidade: 0, unidade: 1 },
  { id: 5, nome: "Bolinho de Carne", preco: 8.0, quantidade: 0, unidade: 1 },

  {
    id: 6,
    nome: "Batata Frita Simples",
    preco: 14.0,
    quantidade: 0,
    unidade: 1,
  },
  {
    id: 7,
    nome: "Batata Frita c/ Calabresa",
    preco: 18.0,
    quantidade: 0,
    unidade: 1,
  },
  { id: 8, nome: "Dadinho de Tapioca", preco: 18.0, quantidade: 0, unidade: 1 },
  { id: 9, nome: "Queijo Empanado", preco: 20.0, quantidade: 0, unidade: 1 },

  { id: 10, nome: "Coca Lata", preco: 5.0, quantidade: 0, unidade: 1 },
  { id: 11, nome: "Fanta Lata", preco: 4.0, quantidade: 0, unidade: 1 },
  { id: 12, nome: "Guaraná Lata", preco: 4.0, quantidade: 0, unidade: 1 },

  {
    id: 13,
    nome: "Mini Coxinha de Frango",
    preco: 14.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 14,
    nome: "Mini Coxinha de Carne",
    preco: 16.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 15,
    nome: "Mini Pastel de Frango",
    preco: 14.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 16,
    nome: "Mini Pastel de Carne",
    preco: 16.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 17,
    nome: "Mini Pastel de Queijo",
    preco: 14.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 18,
    nome: "Croquete de Costela",
    preco: 18.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 19,
    nome: "Croquete de Frango",
    preco: 16.0,
    quantidade: 0,
    unidade: 8,
  },
  {
    id: 20,
    nome: "Bolinha de Calabresa",
    preco: 14.0,
    quantidade: 0,
    unidade: 8,
  },
  { id: 21, nome: "Bolinha de Queijo", preco: 14.0, quantidade: 0, unidade: 8 },

  {
    id: 22,
    nome: "Cento Coxinha de Frango",
    preco: 65.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 23,
    nome: "Cento Bolinha de Carne",
    preco: 65.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 24,
    nome: "Cento Bolinha de Queijo",
    preco: 60.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 25,
    nome: "Cento Risolis de Carne",
    preco: 60.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 26,
    nome: "Cento Quiche de Carne/Frango",
    preco: 60.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 27,
    nome: "Cento Rolinho de Costela",
    preco: 70.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 28,
    nome: "Cento Rolinho de Calabresa",
    preco: 60.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 29,
    nome: "Cento Enrolado de Salsicha",
    preco: 50.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 30,
    nome: "Cento Croquete de Charque",
    preco: 75.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 31,
    nome: "Cento Canudinho de Frango",
    preco: 50.0,
    quantidade: 0,
    unidade: 100,
  },
  {
    id: 32,
    nome: "Cento Dadinho de Tapioca",
    preco: 80.0,
    quantidade: 0,
    unidade: 100,
  },
];
