// products.js
export const allProducts = [
  {
    id: 1,
    name: "Coxinha de Frango",
    price: 8.0,
    quantidade: 1,
    category: "Salgados Grandes",
  },
  {
    id: 2,
    name: "Pastel de Forno",
    price: 7.0,
    quantidade: 1,
    category: "Salgados Grandes",
  },
  {
    id: 3,
    name: "Quiche",
    price: 7.0,
    quantidade: 1,
    category: "Salgados Grandes",
  },
  {
    id: 4,
    name: "Enroladinho",
    price: 6.0,
    quantidade: 1,
    category: "Salgados Grandes",
  },
  {
    id: 5,
    name: "Bolinho de Carne",
    price: 8.0,
    quantidade: 1,
    category: "Salgados Grandes",
  },
  {
    id: 6,
    name: "Batata Frita Simples",
    price: 14.0,
    quantidade: 1,
    category: "Porções de Petiscos",
  },
  {
    id: 7,
    name: "Batata Frita com Calabresa",
    price: 18.0,
    quantidade: 1,
    category: "Porções de Petiscos",
  },
  {
    id: 8,
    name: "Dadinho de Tapioca",
    price: 18.0,
    quantidade: 1,
    category: "Porções de Petiscos",
  },
  {
    id: 9,
    name: "Queijo Empanado",
    price: 20.0,
    quantidade: 1,
    category: "Porções de Petiscos",
  },
  {
    id: 10,
    name: "Coca Lata",
    price: 5.0,
    quantidade: 1,
    category: "bebidas",
  },
  {
    id: 11,
    name: "Fanta Lata",
    price: 4.0,
    quantidade: 1,
    category: "bebidas",
  },
  {
    id: 12,
    name: "Guaraná Lata",
    price: 4.0,
    quantidade: 1,
    category: "bebidas",
  },
  {
    id: 13,
    name: "Mini Coxinha de Frango",
    price: 14.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 14,
    name: "Mini Coxinha de Carne",
    price: 16.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 15,
    name: "Mini Pastel de Frango",
    price: 14.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 16,
    name: "Mini Pastel de Carne",
    price: 16.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 17,
    name: "Mini Pastel de Queijo",
    price: 14.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 18,
    name: "Croquete de Costela",
    price: 18.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 19,
    name: "Croquete de Frango",
    price: 16.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 20,
    name: "Bolinha de Calabresa",
    price: 14.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 21,
    name: "Bolinha de Queijo",
    price: 14.0,
    quantidade: 8,
    category: "Mini Salgados",
  },
  {
    id: 22,
    name: "Coxinha de Frango (Cento)",
    price: 65.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 23,
    name: "Bolinha de Carne (Cento)",
    price: 65.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 24,
    name: "Bolinha de Queijo (Cento)",
    price: 60.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 25,
    name: "Risolis de Carne (Cento)",
    price: 60.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 26,
    name: "Quiche de Carne/Frango (Cento)",
    price: 60.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 27,
    name: "Rolinho de Costela (Cento)",
    price: 70.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 28,
    name: "Rolinho de Calabresa (Cento)",
    price: 60.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 29,
    name: "Enrolado de Salsicha (Cento)",
    price: 50.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 30,
    name: "Croquete de Charque (Cento)",
    price: 75.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 31,
    name: "Canudinho de Frango (Cento)",
    price: 50.0,
    quantidade: 100,
    category: "Porção Cento",
  },
  {
    id: 32,
    name: "Dadinho de Tapioca (Cento)",
    price: 80.0,
    quantidade: 100,
    category: "Porção Cento",
  },
];
